# Generated by Django 6.0.6 on 2026-06-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chấn thương / Vết thương')),
                ('keywords', models.CharField(help_text='Các từ khóa tìm kiếm không dấu cách nhau bằng dấu phẩy, vd: cam mau, chan thuong, vet thuong ho', max_length=255, verbose_name='Từ khóa hệ thống')),
                ('steps_instructions', models.TextField(help_text='Nhập các bước sơ cứu, mỗi bước cách nhau bằng một dấu xuống dòng (Enter)', verbose_name='Các bước hướng dẫn sơ cứu')),
                ('image_illustration', models.ImageField(blank=True, null=True, upload_to='first_aid_images/', verbose_name='Ảnh minh họa thao tác')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bài hướng dẫn sơ cứu',
                'verbose_name_plural': 'Danh sách bài hướng dẫn sơ cứu',
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Tổng yêu cầu cứu hộ')),
                ('completed_requests', models.PositiveIntegerField(default=0, verbose_name='Số yêu cầu đã hoàn thành')),
                ('cancelled_requests', models.PositiveIntegerField(default=0, verbose_name='Số yêu cầu đã hủy')),
                ('average_response_time', models.FloatField(default=0.0, verbose_name='Thời gian phản hồi trung bình (phút)')),
                ('average_distance', models.FloatField(default=0.0, verbose_name='Quãng đường trung bình (km)')),
            ],
            options={
                'verbose_name': 'Thống kê hệ thống',
                'verbose_name_plural': 'Thống kê hệ thống',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RescueStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=20, unique=True, verbose_name='Mã trạm cứu hộ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên trạm cứu hộ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Kinh độ')),
                ('status', models.CharField(choices=[('available', 'Sẵn sàng'), ('busy', 'Đang thực hiện cứu hộ'), ('inactive', 'Tạm ngừng hoạt động')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('vehicle_count', models.PositiveIntegerField(default=1, verbose_name='Số phương tiện cứu hộ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rescue_station', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý')),
            ],
            options={
                'verbose_name': 'Trạm cứu hộ',
                'verbose_name_plural': 'Danh sách trạm cứu hộ',
                'ordering': ['station_code'],
            },
        ),
        migrations.CreateModel(
            name='VictimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(blank=True, max_length=100, verbose_name='Tên người gặp nạn')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tình trạng')),
                ('emergency_level', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Khẩn cấp')], default='medium', max_length=20, verbose_name='Mức độ khẩn cấp')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Vĩ độ người gặp nạn')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Kinh độ người gặp nạn')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ gần đúng')),
                ('location_source', models.CharField(choices=[('gps', 'GPS'), ('three_words', 'Địa chỉ ba từ'), ('map', 'Chọn trên bản đồ')], default='gps', max_length=20, verbose_name='Nguồn vị trí')),
                ('location_accuracy_m', models.FloatField(blank=True, null=True, verbose_name='Độ chính xác GPS (m)')),
                ('what3words_address', models.CharField(blank=True, max_length=100, verbose_name='Địa chỉ ba từ')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ tiếp nhận'), ('assigned', 'Đã phân công trạm'), ('on_the_way', 'Đang trên đường cứu hộ'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi yêu cầu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối')),
                ('assigned_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='portal.rescuestation', verbose_name='Trạm được phân công')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victim_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản gửi yêu cầu')),
            ],
            options={
                'verbose_name': 'Yêu cầu cứu hộ',
                'verbose_name_plural': 'Danh sách yêu cầu cứu hộ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_distance_km', models.FloatField(default=0.0, verbose_name='Quãng đường đề xuất (km)')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Thời gian dự kiến (phút)')),
                ('route_data', models.JSONField(blank=True, help_text='Lưu danh sách tọa độ hoặc dữ liệu tuyến đường do thuật toán hoặc API bản đồ trả về.', null=True, verbose_name='Dữ liệu tuyến đường')),
                ('algorithm', models.CharField(default='A*', max_length=50, verbose_name='Thuật toán định tuyến')),
                ('status', models.CharField(choices=[('assigned', 'Đã phân công'), ('departed', 'Đã xuất phát'), ('arrived', 'Đã đến hiện trường'), ('completed', 'Đã hoàn thành'), ('failed', 'Không thể thực hiện')], default='assigned', max_length=20, verbose_name='Trạng thái xử lý')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian phân công')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rescue_logs', to='portal.rescuestation', verbose_name='Trạm cứu hộ')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_logs', to='portal.victimreport', verbose_name='Yêu cầu cứu hộ')),
            ],
            options={
                'verbose_name': 'Nhật ký cứu hộ',
                'verbose_name_plural': 'Lịch sử cứu hộ',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
