# Generated by Django 4.2.30 on 2026-07-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StormAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề cảnh báo')),
                ('level', models.CharField(choices=[('watch', '🟡 Theo dõi'), ('warning', '🟠 Cảnh báo'), ('emergency', '🔴 Khẩn cấp')], default='watch', max_length=20, verbose_name='Mức độ cảnh báo')),
                ('affected_area', models.CharField(blank=True, help_text='VD: Đà Nẵng, Quảng Nam, Thừa Thiên Huế', max_length=255, verbose_name='Khu vực bị ảnh hưởng')),
                ('description', models.TextField(verbose_name='Nội dung cảnh báo')),
                ('source', models.CharField(blank=True, default='Ban Chỉ huy PCTT tỉnh', max_length=100, verbose_name='Nguồn phát đi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hiệu lực lúc')),
            ],
            options={
                'verbose_name': 'Cảnh báo bão / Thiên tai',
                'verbose_name_plural': 'Danh sách cảnh báo bão',
                'ordering': ['-created_at'],
            },
        ),
    ]
